version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "reisub"
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "reisub"
    groups:
      mix:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
